'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Confederacion
    Public Property ConfederacionID As Integer
    Public Property Nombre As String

    Public Overridable Property Pais As ICollection(Of Pais) = New HashSet(Of Pais)
    Public Overridable Property Torneo As ICollection(Of Torneo) = New HashSet(Of Torneo)

End Class
