'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LogELO
    Public Property LogID As Integer
    Public Property PartidoID As Nullable(Of Integer)
    Public Property EquipoID As Nullable(Of Integer)
    Public Property ELOAnterior As Nullable(Of Double)
    Public Property ELONuevo As Nullable(Of Double)
    Public Property Fecha As Nullable(Of Date)

End Class
