'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FutbolDB2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FutbolDB2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ciudad() As DbSet(Of Ciudad)
    Public Overridable Property Confederacion() As DbSet(Of Confederacion)
    Public Overridable Property Equipo() As DbSet(Of Equipo)
    Public Overridable Property LogELO() As DbSet(Of LogELO)
    Public Overridable Property Pais() As DbSet(Of Pais)
    Public Overridable Property Palmares() As DbSet(Of Palmares)
    Public Overridable Property Partido() As DbSet(Of Partido)
    Public Overridable Property Region() As DbSet(Of Region)
    Public Overridable Property TablaPosiciones() As DbSet(Of TablaPosiciones)
    Public Overridable Property Torneo() As DbSet(Of Torneo)
    Public Overridable Property TorneoAscenso() As DbSet(Of TorneoAscenso)
    Public Overridable Property TorneoDescensos() As DbSet(Of TorneoDescensos)
    Public Overridable Property TorneoEquipo() As DbSet(Of TorneoEquipo)
    Public Overridable Property TorneoPais() As DbSet(Of TorneoPais)
    Public Overridable Property TorneoResultados() As DbSet(Of TorneoResultados)

End Class
