'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Partido
    Public Property PartidoID As Integer
    Public Property TorneoID As Integer
    Public Property EquipoLocalTorneoEquipoID As Integer
    Public Property EquipoVisitanteTorneoEquipoID As Integer
    Public Property GolesLocal As Nullable(Of Integer)
    Public Property GolesVisitante As Nullable(Of Integer)
    Public Property NroFecha As Integer
    Public Property AñoParticipacion As Short
    Public Property Fase As String
    Public Property Grupo As String
    Public Property Estado As String

    Public Overridable Property TorneoEquipo As TorneoEquipo
    Public Overridable Property TorneoEquipo1 As TorneoEquipo
    Public Overridable Property Torneo As Torneo

End Class
