'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Region
    Public Property RegionID As Integer
    Public Property Nombre As String
    Public Property TipoRegion As String
    Public Property PaisID As Integer

    Public Overridable Property Ciudad As ICollection(Of Ciudad) = New HashSet(Of Ciudad)
    Public Overridable Property Equipo As ICollection(Of Equipo) = New HashSet(Of Equipo)
    Public Overridable Property Pais As Pais
    Public Overridable Property Torneo As ICollection(Of Torneo) = New HashSet(Of Torneo)

End Class
