'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TablaPosiciones
    Public Property TablaPosicionesID As Integer
    Public Property TorneoID As Integer
    Public Property AñoParticipacion As Short
    Public Property EquipoID As Integer
    Public Property PJ As Integer
    Public Property PG As Integer
    Public Property PE As Integer
    Public Property PP As Integer
    Public Property GF As Integer
    Public Property GC As Integer
    Public Property DG As Integer
    Public Property PTS As Integer
    Public Property Fase As String
    Public Property Grupo As String

    Public Overridable Property Equipo As Equipo
    Public Overridable Property Torneo As Torneo

End Class
