'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TorneoResultados
    Public Property TorneoResultadosID As Integer
    Public Property TorneoID As Integer
    Public Property AñoTorneo As Short
    Public Property CampeonEquipoID As Nullable(Of Integer)
    Public Property SubcampeonEquipoID As Nullable(Of Integer)
    Public Property Observaciones As String
    Public Property Era As String

    Public Overridable Property Equipo As Equipo
    Public Overridable Property Equipo1 As Equipo
    Public Overridable Property Torneo As Torneo

End Class
