'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TorneoAscenso
    Public Property TorneoAscensoID As Integer
    Public Property AscensoTorneoEquipoID As Integer
    Public Property TorneoOrigenID As Integer
    Public Property TorneoDestinoID As Integer
    Public Property AñoAscenso As Short

    Public Overridable Property Torneo As Torneo
    Public Overridable Property Torneo1 As Torneo
    Public Overridable Property TorneoEquipo As TorneoEquipo

End Class
