'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TorneoEquipo
    Public Property TorneoEquipoID As Integer
    Public Property TorneoID As Integer
    Public Property EquipoID As Integer
    Public Property AñoParticipacion As Short
    Public Property Fase As String
    Public Property Grupo As String

    Public Overridable Property Equipo As Equipo
    Public Overridable Property Partido As ICollection(Of Partido) = New HashSet(Of Partido)
    Public Overridable Property Partido1 As ICollection(Of Partido) = New HashSet(Of Partido)
    Public Overridable Property Torneo As Torneo
    Public Overridable Property TorneoAscenso As ICollection(Of TorneoAscenso) = New HashSet(Of TorneoAscenso)
    Public Overridable Property TorneoDescensos As ICollection(Of TorneoDescensos) = New HashSet(Of TorneoDescensos)

End Class
