'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Torneo
    Public Property TorneoID As Integer
    Public Property Nombre As String
    Public Property TipoTorneo As String
    Public Property Categoria As String
    Public Property ConfederacionID As Nullable(Of Integer)
    Public Property PaisID As Nullable(Of Integer)
    Public Property RegionID As Nullable(Of Integer)
    Public Property CiudadID As Nullable(Of Integer)
    Public Property Estado As String

    Public Overridable Property Ciudad As Ciudad
    Public Overridable Property Confederacion As Confederacion
    Public Overridable Property Pais As Pais
    Public Overridable Property Palmares As ICollection(Of Palmares) = New HashSet(Of Palmares)
    Public Overridable Property Partido As ICollection(Of Partido) = New HashSet(Of Partido)
    Public Overridable Property Region As Region
    Public Overridable Property TablaPosiciones As ICollection(Of TablaPosiciones) = New HashSet(Of TablaPosiciones)
    Public Overridable Property TorneoAscenso As ICollection(Of TorneoAscenso) = New HashSet(Of TorneoAscenso)
    Public Overridable Property TorneoAscenso1 As ICollection(Of TorneoAscenso) = New HashSet(Of TorneoAscenso)
    Public Overridable Property TorneoDescensos As ICollection(Of TorneoDescensos) = New HashSet(Of TorneoDescensos)
    Public Overridable Property TorneoDescensos1 As ICollection(Of TorneoDescensos) = New HashSet(Of TorneoDescensos)
    Public Overridable Property TorneoEquipo As ICollection(Of TorneoEquipo) = New HashSet(Of TorneoEquipo)
    Public Overridable Property TorneoPais As ICollection(Of TorneoPais) = New HashSet(Of TorneoPais)
    Public Overridable Property TorneoResultados As ICollection(Of TorneoResultados) = New HashSet(Of TorneoResultados)

End Class
